name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"

jobs:
  run_tests:
    name: tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
        toxenv: [quality, docs, pii_check, django42]
    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip
        run: pip install -r requirements/pip.txt

      - name: Install Dependencies
        run: pip install -r requirements/ci.txt

      - name: Run Tests
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox

      - name: Run coverage
        # Skip Codecov on forked PRs and when token is not available (e.g., protected branches or private repos).
        if: |
          matrix.python-version == '3.12' &&
          matrix.toxenv == 'django42' &&
          (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false) &&
          env.CODECOV_TOKEN != ''
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          token: ${{ env.CODECOV_TOKEN }}
          flags: unittests
          fail_ci_if_error: true
